# -*- coding: utf-8 -*-
"""Calculadora.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BzIxC-Oo09HqqT5RLFDwnN_aaoKp19sb
"""

class calculadora:
    """
    Implementación de calculadora usando programación orientada en objetos
    """

    def __init__(self,n1,n2):
        self.n1 = float(n1)
        self.n2 = float(n2)
    
    def sumar(n1, n2):
        return n1 + n2
    
    def restar(n1 ,n2):
        return n1 - n2

    def multiplicar(n1,n2):
        return n1 * n2
        
    def dividir(n1,n2):
        return n1 / n2